// Generated by CoffeeScript 1.9.0
(function() {
  var makeAjaxRequest, renderRun;

  $('.discussion-timeline-actions').before(this.holderTmpl());

  makeAjaxRequest = function(options) {
    return $.ajax({
      type: options.type || "GET",
      url: "https://app.rainforestqa.com/api/1/" + options.endpoint,
      dataType: "json",
      data: options.data || {},
      headers: {
        CLIENT_TOKEN: "08b8bc4f0cec845a37f9266918e83e98"
      },
      success: (function(_this) {
        return function(data) {
          return typeof options.success === "function" ? options.success(data) : void 0;
        };
      })(this)
    });
  };

  renderRun = function(run) {
    return $(".rainforest-run-history").append(this.runHistoryItemTmpl(run));
  };

  makeAjaxRequest({
    endpoint: "runs",
    data: {
      state: "in_progress"
    },
    success: (function(_this) {
      return function(data) {
        var i, run, _i, _len, _results;
        _results = [];
        for (i = _i = 0, _len = data.length; _i < _len; i = ++_i) {
          run = data[i];
          _results.push(renderRun(run));
        }
        return _results;
      };
    })(this)
  });

  makeAjaxRequest({
    endpoint: "environments",
    success: function(data) {
      var env, i, selected, _i, _len, _results;
      _results = [];
      for (i = _i = 0, _len = data.length; _i < _len; i = ++_i) {
        env = data[i];
        selected = env["default"] === true ? "selected" : "";
        _results.push($('.rainforest-envs').append("<option value='" + env.id + "' " + selected + ">" + env.name + "</option>"));
      }
      return _results;
    }
  });

  makeAjaxRequest({
    endpoint: "tests/tags",
    success: function(data) {
      var i, tag, _i, _len, _results;
      _results = [];
      for (i = _i = 0, _len = data.length; _i < _len; i = ++_i) {
        tag = data[i];
        _results.push($('.rainforest-tags').append("<option value='" + tag.name + "'>" + tag.name + "</option>"));
      }
      return _results;
    }
  });

  $('.run-rainforest').on("click", function() {
    var env, requestOptions, tag;
    env = $('.rainforest-envs').val();
    tag = $('.rainforest-tags').val();
    requestOptions = {
      environment_id: env
    };
    if (tag === "all") {
      requestOptions["tests"] = "all";
    } else {
      requestOptions["tags"] = [tag];
    }
    return makeAjaxRequest({
      type: "POST",
      endpoint: "runs",
      data: requestOptions,
      success: (function(_this) {
        return function(data) {
          return renderRun(data);
        };
      })(this)
    });
  });

}).call(this);
